P5/urls.py
from django.contrib import admin
from django.urls import path,include
import yogi
from yogi import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('primary suffix',include("appname.urls"))
    path('yogi/',include("yogi.urls")),
    path('yokesh/',views.yokesh,name="sample")
]

yogi/urls.py
from django.urls import path
from yogi import views

app_name="yogi"#is used to creatq a namespace
urlpatterns = [
    #path("secondary suffix",address of function, name of mapping)
    path('',views.index,name='index'),
    path('home',views.home,name="home"),
    path('fact/<n>',views.fact,name="fact"),
    path('child/',views.child,name="child"),
]

yogi/models.py
from django.db import models

# Create your models here.

yogi/views.py
from django.shortcuts import render
from django.http import HttpResponse
from math import factorial
# Create your views here.

def index(request):
    return HttpResponse("<h1>welcome to views of my app</h1>")

def home(request):
    return render(request,"yogi/home.html",{'name':"Yokesh"})

def fact(request,n):
    n=int(n)
    return HttpResponse("<h4>factorial is {}</h4>".format(factorial(n)))

def child(request):
    return render(request,"child.html")

def yokesh(request):
    return render(request,"yogi/yokesh.html")

templates/child.html
{% extends "yogi/base.html" %}

{% block title %}
  <title>Child HTML File</title>
{% endblock %}

<!--
  {% block body_block %}
<body>
    <h1>Welcome to child.html</h1>
</body>
{% endblock %}
-->

{% block content %}
  <h1>Welcome to content</h1>
  <a href="{% url 'yogi:home' %}">home</a>
  <a href="{% url 'sample' %}">sample</a>
{% endblock %}

templates/yogi/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>TEMPLATE INHERITANCE</title>
    {% endblock %}
</head>
<!--
{% block body_block %}
<body>
    <h1>Navbar</h1>
        <h1>Wlecome to Base.html</h1>
</body>
{% endblock %}
-->

<body>
    <h1>Navbar</h1>
    {% block content %}
        <h1>Wlecome to Base.html</h1>
    {% endblock %}
</body>

</html>

templates/yogi/home.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>html demo</title>
</head>
<body>
    <h2>welcome to html page</h2>
    <h3>{{name}}</h3>
</body>
</html>

templates/yogi/yokesh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Yokesh</title>
</head>
<body>
    <h2>welcome to yokesh html</h2>
    <h3>{{name}}</h3>
    <a href="{% url 'yogi:child' %}">Child</a>
    <a href="{% url 'yogi:home' %}">Home</a>
</body>
</html>